// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwawybybmiiyjyewgbnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3YXd5YnlibWlpeWp5ZXdnYm5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwNzQ4MDEsImV4cCI6MjA3NzY1MDgwMX0.OFlAOXwkkBChjNvPkWrLmTopBsRc5zrC77KVeXeGt5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});